In [1]:
from nanobt.utils import load_file
import polars as pl

_, _, df_future = load_file(
    "/share/tardis/raw/binance-futures/book_ticker/BTCUSDT/binance-futures_book_ticker_2025-11-01_BTCUSDT.csv.gz",
    to_numpy=False,
)
_, _, df_spot = load_file(
    "/share/tardis/raw/binance/book_ticker/BTCUSDT/binance_book_ticker_2025-11-01_BTCUSDT.csv.gz",
    to_numpy=False,
)

Reading /share/tardis/raw/binance-futures/book_ticker/BTCUSDT/binance-futures_book_ticker_2025-11-01_BTCUSDT.csv.gz
Reading /share/tardis/raw/binance/book_ticker/BTCUSDT/binance_book_ticker_2025-11-01_BTCUSDT.csv.gz

In [2]:
df_future = df_future.to_pandas()

In [3]:
df_spot = df_spot.to_pandas()

In [4]:
df_future

,exch_ts,local_ts,ask_px,ask_qty,bid_px,bid_qty
0,1761955200002000000,1761955200006838000,109557.3,1.666,109557.2,5.220
1,1761955200002000000,1761955200006839000,109557.3,1.666,109557.2,5.229
2,1761955200008000000,1761955200010685000,109557.3,1.666,109557.2,5.233
3,1761955200016000000,1761955200019167000,109557.3,1.666,109557.2,5.223
4,1761955200042000000,1761955200044786000,109557.3,1.692,109557.2,5.223
...,...,...,...,...,...,...
13435966,1762041599940000000,1762041599942854000,110047.3,4.810,110047.2,6.703
13435967,1762041599952000000,1762041599954820000,110047.3,4.806,110047.2,6.703
13435968,1762041599975000000,1762041599977126000,110047.3,4.806,110047.2,6.701
13435969,1762041599988000000,1762041599990063000,110047.3,4.812,110047.2,6.701
13435970,1762041599992000000,1762041599994382000,110047.3,4.806,110047.2,6.701

In [5]:
df_spot

,exch_ts,local_ts,ask_px,ask_qty,bid_px,bid_qty
0,1761955200100031000,1761955200100031000,109608.01,5.83190,109608.00,1.18446
1,1761955200102626000,1761955200102626000,109608.01,5.83309,109608.00,1.18446
2,1761955200107157000,1761955200107157000,109608.01,5.83190,109608.00,1.18446
3,1761955200118127000,1761955200118127000,109608.01,5.83190,109608.00,1.18451
4,1761955200119118000,1761955200119118000,109608.01,5.83190,109608.00,1.18446
...,...,...,...,...,...,...
11213204,1762041599688931000,1762041599688931000,110098.10,7.92600,110098.09,3.07495
11213205,1762041599695008000,1762041599695008000,110098.10,7.92886,110098.09,3.07495
11213206,1762041599848116000,1762041599848116000,110098.10,7.92886,110098.09,2.75995
11213207,1762041599917989000,1762041599917989000,110098.10,7.92891,110098.09,2.75995
11213208,1762041599992957000,1762041599992957000,110098.10,7.92891,110098.09,2.76233

In [10]:
df = df_future.merge(
    df_spot,
    on="exch_ts",
    suffixes=("_future", "_spot"),
    how="outer",
)
df

,exch_ts,local_ts_future,ask_px_future,ask_qty_future,bid_px_future,bid_qty_future,local_ts_spot,ask_px_spot,ask_qty_spot,bid_px_spot,bid_qty_spot
0,1761955200002000000,1.761955e+18,109557.3,1.666,109557.2,5.220,NaN,NaN,NaN,NaN,NaN
1,1761955200002000000,1.761955e+18,109557.3,1.666,109557.2,5.229,NaN,NaN,NaN,NaN,NaN
2,1761955200008000000,1.761955e+18,109557.3,1.666,109557.2,5.233,NaN,NaN,NaN,NaN,NaN
3,1761955200016000000,1.761955e+18,109557.3,1.666,109557.2,5.223,NaN,NaN,NaN,NaN,NaN
4,1761955200042000000,1.761955e+18,109557.3,1.692,109557.2,5.223,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
24647254,1762041599952000000,1.762042e+18,110047.3,4.806,110047.2,6.703,NaN,NaN,NaN,NaN,NaN
24647255,1762041599975000000,1.762042e+18,110047.3,4.806,110047.2,6.701,NaN,NaN,NaN,NaN,NaN
24647256,1762041599988000000,1.762042e+18,110047.3,4.812,110047.2,6.701,NaN,NaN,NaN,NaN,NaN
24647257,1762041599992000000,1.762042e+18,110047.3,4.806,110047.2,6.701,NaN,NaN,NaN,NaN,NaN
24647258,1762041599992957000,NaN,NaN,NaN,NaN,NaN,1.762042e+18,110098.1,7.92891,110098.09,2.76233

In [14]:
df = df.ffill().bfill()
df

,exch_ts,local_ts_future,ask_px_future,ask_qty_future,bid_px_future,bid_qty_future,local_ts_spot,ask_px_spot,ask_qty_spot,bid_px_spot,bid_qty_spot
0,1761955200002000000,1.761955e+18,109557.3,1.666,109557.2,5.220,1.761955e+18,109608.01,5.83190,109608.00,1.18446
1,1761955200002000000,1.761955e+18,109557.3,1.666,109557.2,5.229,1.761955e+18,109608.01,5.83190,109608.00,1.18446
2,1761955200008000000,1.761955e+18,109557.3,1.666,109557.2,5.233,1.761955e+18,109608.01,5.83190,109608.00,1.18446
3,1761955200016000000,1.761955e+18,109557.3,1.666,109557.2,5.223,1.761955e+18,109608.01,5.83190,109608.00,1.18446
4,1761955200042000000,1.761955e+18,109557.3,1.692,109557.2,5.223,1.761955e+18,109608.01,5.83190,109608.00,1.18446
...,...,...,...,...,...,...,...,...,...,...,...
24647254,1762041599952000000,1.762042e+18,110047.3,4.806,110047.2,6.703,1.762042e+18,110098.10,7.92891,110098.09,2.75995
24647255,1762041599975000000,1.762042e+18,110047.3,4.806,110047.2,6.701,1.762042e+18,110098.10,7.92891,110098.09,2.75995
24647256,1762041599988000000,1.762042e+18,110047.3,4.812,110047.2,6.701,1.762042e+18,110098.10,7.92891,110098.09,2.75995
24647257,1762041599992000000,1.762042e+18,110047.3,4.806,110047.2,6.701,1.762042e+18,110098.10,7.92891,110098.09,2.75995
24647258,1762041599992957000,1.762042e+18,110047.3,4.806,110047.2,6.701,1.762042e+18,110098.10,7.92891,110098.09,2.76233

In [21]:
df['ratio'] = (df['ask_px_future'] + df['bid_px_future'])  / (df['ask_px_spot'] + df['bid_px_spot'] ) - 1
df['ratio_med'] = df['ratio'].rolling(window=200).median()


df['ratio'].mean(), df['ratio'].std(), df['ratio'].min(), df['ratio'].max()

(np.float64(-0.0003832646348531131),
 np.float64(8.423496753165112e-05),
 np.float64(-0.0011411602645221564),
 np.float64(0.00025650069516580665))